// Generated by Game Polish Lab. Visual style values only.
export interface FarmSlotStyle {
  slotWidth: number;
  slotHeight: number;
  gap: number;
  cornerRadius: number;
  selectedGlowStrength: number;
  fillColor: string;
  innerFillColor: string;
  borderWidth: number;
  borderColor: string;
  lockedOverlayOpacity: number;
  emptySlotOpacity: number;
  mergeCandidatePulseScale: number;
  monsterDisplayScale: number;
  monsterVerticalOffset: number;
}

export type FarmSlotRuntimeLiveStyle = Partial<Pick<FarmSlotStyle, "fillColor" | "innerFillColor" | "borderWidth" | "borderColor" | "lockedOverlayOpacity" | "emptySlotOpacity" | "mergeCandidatePulseScale" | "monsterDisplayScale" | "monsterVerticalOffset">>;

export const DEFAULT_FARM_SLOT_STYLE: FarmSlotStyle = {
  "slotWidth": 108,
  "slotHeight": 108,
  "gap": 12,
  "cornerRadius": 10,
  "selectedGlowStrength": 0.4,
  "fillColor": "#aadf78",
  "innerFillColor": "#aadf78",
  "borderWidth": 3,
  "borderColor": "#469247",
  "lockedOverlayOpacity": 0.58,
  "emptySlotOpacity": 0.52,
  "mergeCandidatePulseScale": 1.08,
  "monsterDisplayScale": 0.9,
  "monsterVerticalOffset": -4
};

export const FARM_SLOT_STYLE: FarmSlotStyle = { ...DEFAULT_FARM_SLOT_STYLE };

const LIVE_STYLE_PATH = '/.game-polish-lab/live-style/farm-slot.json';
const LIVE_POLL_INTERVAL_MS = 300;

let lastLivePayload = '';
let lastLivePollAt = 0;
let livePollInFlight = false;

export async function pollFarmSlotLiveStyle(now = Date.now()): Promise<boolean> {
  const env = (import.meta as unknown as { env?: { DEV?: boolean } }).env;
  if (!env?.DEV || typeof fetch !== 'function') {
    return false;
  }
  if (livePollInFlight || now - lastLivePollAt < LIVE_POLL_INTERVAL_MS) {
    return false;
  }

  livePollInFlight = true;
  lastLivePollAt = now;
  try {
    const response = await fetch(LIVE_STYLE_PATH, { cache: 'no-store' });
    if (response.status === 404) {
      return applyFarmSlotStylePayload('');
    }
    if (!response.ok) {
      return false;
    }
    return applyFarmSlotStylePayload(await response.text());
  } catch {
    return false;
  } finally {
    livePollInFlight = false;
  }
}

function applyFarmSlotStylePayload(payload: string): boolean {
  if (payload === lastLivePayload) {
    return false;
  }
  lastLivePayload = payload;
  const next = payload ? normalizeLiveFarmSlotStyle(payload) : DEFAULT_FARM_SLOT_STYLE;
  const before = JSON.stringify(FARM_SLOT_STYLE);
  Object.assign(FARM_SLOT_STYLE, next);
  return JSON.stringify(FARM_SLOT_STYLE) !== before;
}

function normalizeLiveFarmSlotStyle(payload: string): FarmSlotStyle {
  try {
    const parsed = JSON.parse(payload) as { values?: unknown };
    const source = parsed && typeof parsed === 'object' && parsed.values && typeof parsed.values === 'object'
      ? parsed.values as Record<string, unknown>
      : parsed as Record<string, unknown>;
    return {
      ...DEFAULT_FARM_SLOT_STYLE,
      fillColor: color(source.fillColor, DEFAULT_FARM_SLOT_STYLE.fillColor),
      innerFillColor: color(source.innerFillColor, DEFAULT_FARM_SLOT_STYLE.innerFillColor),
      borderColor: color(source.borderColor, DEFAULT_FARM_SLOT_STYLE.borderColor),
      borderWidth: numberInRange(source.borderWidth, DEFAULT_FARM_SLOT_STYLE.borderWidth, 0, 10),
      emptySlotOpacity: numberInRange(source.emptySlotOpacity, DEFAULT_FARM_SLOT_STYLE.emptySlotOpacity, 0, 1),
      lockedOverlayOpacity: numberInRange(source.lockedOverlayOpacity, DEFAULT_FARM_SLOT_STYLE.lockedOverlayOpacity, 0, 1),
      monsterDisplayScale: numberInRange(source.monsterDisplayScale, DEFAULT_FARM_SLOT_STYLE.monsterDisplayScale, 0.55, 1.35),
      monsterVerticalOffset: numberInRange(source.monsterVerticalOffset, DEFAULT_FARM_SLOT_STYLE.monsterVerticalOffset, -28, 28),
      mergeCandidatePulseScale: numberInRange(source.mergeCandidatePulseScale, DEFAULT_FARM_SLOT_STYLE.mergeCandidatePulseScale, 1, 1.28),
    };
  } catch {
    return DEFAULT_FARM_SLOT_STYLE;
  }
}

function color(value: unknown, fallback: string): string {
  return typeof value === 'string' && /^#[0-9a-f]{6}$/i.test(value) ? value : fallback;
}

function numberInRange(value: unknown, fallback: number, min: number, max: number): number {
  return typeof value === 'number' && Number.isFinite(value)
    ? Math.min(max, Math.max(min, value))
    : fallback;
}
